Infineon/arduino-core-tests

Makefile, README.md, src/corelibs/digitalio/test_digitalio_single.cpp, src/corelibs/time/test_time_single.cpp, src/test_main.ino
=> Add time and digital io tests

Makefile, src/corelibs/wifi/test_wifi_client.cpp, src/corelibs/wifi/test_wifi_server.cpp, src/test_main.ino
Review after #10 
Added wifi client and server tests. Currently only server begin() - client connect(). Associated to https://github.com/Infineon/arduino-core-psoc/pull/55
=> Wifi client server basic

src/corelibs/wifi/test_wifi_client.cpp, src/corelibs/wifi/test_wifi_server.cpp
Wifi server and client read() write() exchange.
=> src/corelibs/wifi: Added client and server write/read functions.

.gitignore, Makefile, src/corelibs/wifi/test_wifi_client.cpp, src/corelibs/wifi/test_wifi_extras.cpp, src/corelibs/wifi/test_wifi_server.cpp, src/test_main.ino
This PR is to shall be reviewed after #11.
These tests complete the WiFiClient and WiFiServer API happy path use cases. 
SSL functions still not implemented.
=> Wifi server client completion tests

src/corelibs/wifi/test_wifi_ap.cpp, src/corelibs/wifi/test_wifi_extras.cpp, src/corelibs/wifi/test_wifi_server.cpp, src/corelibs/wifi/test_wifi_sta.cpp
* Added gatewayIP() and hostByName() function tests.
=> WiFi core-lib: Added gatewayIP() and hostByName() tests.

src/corelibs/wifi/test_wifi_ap.cpp, src/corelibs/wifi/test_wifi_client.cpp, src/corelibs/wifi/test_wifi_extras.cpp, src/corelibs/wifi/test_wifi_server.cpp, src/corelibs/wifi/test_wifi_sta.cpp
Added WiFi.disconnect() sunny side tests.
=> Wifi disconnect

.gitignore, Makefile, src/corelibs/time/test_time_single.cpp, src/corelibs/wifi/test_wifi_ap.cpp, src/corelibs/wifi/test_wifi_client.cpp, src/corelibs/wifi/test_wifi_extras.cpp, src/corelibs/wifi/test_wifi_server.cpp, src/corelibs/wifi/test_wifi_sta.cpp, src/test_main.ino
* Aggregated PR for wifi tests.
=> Wifi net api

Makefile, src/corelibs/spi/test_spi_connected1_loopback.cpp, src/test_main.ino
test cases for SPI loopback test without interrupts functionality.
=> Add spi test transfer

src/corelibs/wifi/test_wifi_ap.cpp, src/corelibs/wifi/test_wifi_sta.cpp
* Added tests for WiFiClass connection settings functions.
=> WiFi library: Added tests for WiFi connection setting functions.

src/corelibs/wifi/test_wifi_sta.cpp
=> WiFi library: Added scanNetworks() tests.

src/corelibs/wifi/test_wifi_ap.cpp, src/corelibs/wifi/test_wifi_extras.cpp, src/corelibs/wifi/test_wifi_sta.cpp
To be reviewed after #22.
* Added WiFi.dnsIP() tests
=> WiFi lib: Added dnsIP() tests.

Makefile, src/corelibs/spi/test_spi_connected1_loopback.cpp, src/corelibs/spi/test_spi_connected2_masterpingpong.cpp, src/corelibs/spi/test_spi_connected2_slavepingpong.cpp, src/test_common_includes.h, src/test_main.ino
Added SPI Master Slave pingpong tests.
Attached the test log screenshots. Let me know if you need the LA capture(I was not able to attach it here) also to have a look.
=> Implement SPI master slave ping pong tests.

src/corelibs/wifi/test_wifi_ap.cpp, src/corelibs/wifi/test_wifi_client.cpp, src/corelibs/wifi/test_wifi_extras.cpp, src/corelibs/wifi/test_wifi_server.cpp, src/corelibs/wifi/test_wifi_sta.cpp
=> src/corelibs/wifi: Documented wifi tests.

src/corelibs/wifi/test_wifi_extras.cpp
=> Test for SetDNS.

Makefile, src/corelibs/wifi/test_wifi_exceptions.cpp, src/test_main.ino
This test will raise and exception ie, WiFi connection fails due to timeout
=>  src: Exception test for timeout.

Makefile, src/corelibs/uart/test_uart_rx.cpp, src/corelibs/uart/test_uart_tx.cpp, src/test_main.ino
Alternative uart tests. 
I was unable to synchronize the existing ones. Added an extra pin for synchronization, and break down in smaller steps as per functionality of the API.
=> UART: Added alternative UART tests.

src/corelibs/wifi/test_wifi_sta.cpp
=>  src/corelibs/wifi/test_wifi_sta.cpp: WiFi get channel test.

Makefile, src/corelibs/analogio/test_analogio_single.cpp, src/test_main.ino
Test cases for Analog read on ADC pin implemented [
](url)
=> src/corelibs/analogio: Add analog ADC tests.

Makefile, src/corelibs/wifi/test_wifi_udp_client.cpp, src/corelibs/wifi/test_wifi_udp_server.cpp, src/test_main.ino
=> Wifi udp begin packet

src/corelibs/wifi/test_wifi_udp_server.cpp
=> udp stop test

src/corelibs/wifi/test_wifi_udp_client.cpp, src/corelibs/wifi/test_wifi_udp_server.cpp
=>  src/corelibs: Write test.

src/corelibs/wifi/test_wifi_udp_client.cpp, src/corelibs/wifi/test_wifi_udp_server.cpp
=> Wi fi udp endpacket

Makefile, src/corelibs/tone/test_tone_no_tone.cpp, src/test_main.ino, src/utils/Utilities.hpp
Implemented tests for Tone APIs:
=> src/corelibs/tone: src/utils: Implement tests for Tone and noTone APIs.

Makefile, src/corelibs/random/test_random.cpp, src/test_main.ino
=> Add random tests

src/corelibs/wifi/test_wifi_udp_client.cpp, src/corelibs/wifi/test_wifi_udp_server.cpp
=>  src/corelibs: Test for beginMulticast.

src/corelibs/digitalio/test_digitalio_single.cpp
=>  src/corelibs/digitalio: Refactor tests after the deinit implementation.

src/corelibs/digitalio/test_digitalio_single.cpp
Refactor the tests to support the GPIO Reinitialization feature
=>  src/corelibs: Extended test for GPIO reinit.

Makefile, src/corelibs/wire/test_wire_connected1_pingpong.cpp, src/corelibs/wire/test_wire_connected2_masterpingpong.cpp, src/corelibs/wire/test_wire_connected2_slavepingpong.cpp, src/test_common_includes.h, src/test_main.ino, src/test_synchronisation.cpp, src/test_synchronisation.h
Description
Provide the information we need to review your PR. What problem does the pull request solve? "Bug fix" is not a good description.
Related Issue
If you opened an issue before creating the PR, point to it here.
Context
What do we need to know about your development environment, tools, target, and so on. Screenshots are always helpful if there is a UI element to this PR.
=> Add test synchronization

Makefile
Description
Remove redundancy for test name check.
Related Issue
Context
=> Makefile: Remove redundancy.

src/corelibs/wifi/test_wifi_ap.cpp
Add synchronization to the wifi ap_sta multiboard test.
=> src/corelibs/wifi/test_wifi_ap.cpp: Wait for station to connect.

src/corelibs/spi/test_spi_connected2_masterpingpong.cpp
Description
Fix Compilation error.
Related Issue
Not guarded properly. After #ifndef not closed properly, 
Context
Fixed compilation error.
=> src/corelibs/spi: Compilation error fix.

src/corelibs/wifi/test_wifi_sta.cpp
* Re-enabled again wifi-sta `wifi.scanNetworks()` test.
=> src/corelibs/wifi/test_wifi_sta.cpp: Enabled scanNetworks tests.

Makefile.multiboard_test
Enable more tests in Makefile.multiboard_test.
=> enable tests in Makefile.multiboard_test
